# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repoant < Formula
  desc "Delete and mass delete GitHub repositories interactively"
  homepage "https://github.com/AasishDairelSahayaGrinspan/RepoAnt"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AasishDairelSahayaGrinspan/RepoAnt/releases/download/v0.3.2/repoant_darwin_amd64.tar.gz"
      sha256 "aa9d64d5bd40518602cea45e1122089c139279c40bd3b4c7370ee573e736b862"

      define_method(:install) do
        bin.install "repoant"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AasishDairelSahayaGrinspan/RepoAnt/releases/download/v0.3.2/repoant_darwin_arm64.tar.gz"
      sha256 "da525399fe50fc7bf4ec153bcfbc93ca03ec43295be4feb65eb6048493346e14"

      define_method(:install) do
        bin.install "repoant"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AasishDairelSahayaGrinspan/RepoAnt/releases/download/v0.3.2/repoant_linux_amd64.tar.gz"
      sha256 "1829e8d9781bc0fc7043ea15a2534055a0bcc7b19b59b4fb82232b0431efdb95"
      define_method(:install) do
        bin.install "repoant"
      end
    end
  end

  test do
    system "#{bin}/repoant", "version"
  end
end
